[package]
name = "intrico-core"
version = "2.1.1"
edition = "2024"
description = "Core execution engine and circuit primitives for Intrico quantum computing."
authors = ["Soham Ghugare <soham.ghugare@gmail.com>"]
keywords = [
    "quantum-computing",
    "quantum-technology",
    "quantum-sdk",
    "quantum",
    "rust",
]
categories = ["development-tools", "science", "simulation"]
license = "Apache-2.0"
repository = "https://github.com/Intrico-Labs/intrico"
[dependencies]
rand = "0.10.0"
rusticle = "2.0.0"
