use rusticle::Matrix;
use smallvec::SmallVec;

use crate::core::{Amplitude, QuantumGate};

/// The CompiledCircuit gate that is returned after transpiling a Circuit IR
pub struct CompiledCircuit {
    num_qubits: usize,
    optimization_level: u8,
    ops: Vec<NativeOp>,
    fused_ops: Vec<FusedOp>,
    measurements: Vec<MeasurementOp>,
    creg_size: usize,
    creg_mapping: Vec<(usize, usize)>,
    metadata: CompiledCircuitMetadata,
}

/// A NativeOp is a low-level interpretation of the GateOp
pub struct NativeOp {
    gate: QuantumGate,
    params: [usize; 3],
    controls: SmallVec<[usize; 2]>,
    targets: SmallVec<[usize; 2]>
}

pub struct FusedOp {
    op_index: usize,
    matrix: Matrix<Amplitude>
}

pub struct MeasurementOp {
    qubit_index: usize,
    creg_index: usize
}

pub struct CompiledCircuitMetadata {
    depth: Option<usize>
}


/// The ExecutionContext holds everything about the Quantum State
/// This is generated by preparing the CompiledCircuit for execution
pub struct ExecutionContext {
    
}