use std::{sync::Arc};

use crate::{backend::{CompiledCircuit, NativeOp}, core::{Amplitude}};



#[derive(Clone)]
pub enum PrecomputedGate {
    OneQ([Amplitude; 4]),
    TwoQ([Amplitude; 16]),
    None,
}

/// The ExecutionContext holds everything about the Quantum State
/// This is generated by preparing the CompiledCircuit for execution
pub struct ExecutionContext {
    compiled_ref: Arc<CompiledCircuit>,
    statevector: Vec<Amplitude>,
    pub(crate) precomputed: Vec<PrecomputedGate>,
    rng_seed: Option<usize>,
    // metrics: ExecutionMetrics
}

impl ExecutionContext {
    pub fn new(compiled_circuit: Arc<CompiledCircuit>, rng_seed: Option<usize>) -> Self {

        let dimension = 1 << compiled_circuit.num_qubits();

        // create new statevector and set to ket 00..0
        let mut statevector = vec![Amplitude::new(0.0, 0.0); dimension];
        statevector[0] = Amplitude::new(1.0, 0.0);


        ExecutionContext {
            compiled_ref: compiled_circuit,
            statevector,
            precomputed: vec![],
            rng_seed
        }
    }

    pub fn compiled_ref(&self) -> &Arc<CompiledCircuit> {
        &self.compiled_ref
    }

    pub fn compiled_ops(&self) -> &[NativeOp] {
        self.compiled_ref.ops()
    }

    pub fn statevector(&mut self) -> &mut [Amplitude] {
        self.statevector.as_mut_slice()
    }

    pub fn precomputed(&self) -> &[PrecomputedGate] {
        &self.precomputed
    }

    pub fn rng_seed(&self) -> Option<usize> {
        self.rng_seed
    }
}