use rusticle::Matrix;
use smallvec::SmallVec;
use std::fmt::Debug;

use crate::core::{Amplitude, QuantumGate};

/// The CompiledCircuit gate that is returned after transpiling a Circuit IR
pub struct CompiledCircuit {
    num_qubits: usize,
    optimization_level: u8,
    ops: Vec<NativeOp>,
    fused_ops: Vec<FusedOp>,
    measurements: Vec<MeasurementOp>,
    creg_size: usize,
    creg_mapping: Vec<(usize, usize)>,
    metadata: CompiledCircuitMetadata,
}

/// A NativeOp is a low-level interpretation of the GateOp
#[derive(Debug)]
pub struct NativeOp {
    gate: QuantumGate,
    params: Option<[f64; 3]>,
    controls: SmallVec<[usize; 2]>,
    targets: SmallVec<[usize; 2]>
}

impl NativeOp {
    pub fn new(gate: QuantumGate, params: Option<[f64; 3]>, controls: SmallVec<[usize; 2]>, targets: SmallVec<[usize; 2]>) -> Self {
        Self {
            gate,
            params,
            controls,
            targets
        }
    }
}

#[derive(Debug)]
pub struct FusedOp {
    op_index: usize,
    matrix: Matrix<Amplitude>
}

impl FusedOp {
    pub fn new(op_index: usize, matrix: Matrix<Amplitude>) -> Self {
        Self {
            op_index,
            matrix
        }
    }
}

#[derive(Debug)]
pub struct MeasurementOp {
    qubit_index: usize,
    creg_index: usize
}

impl MeasurementOp {
    pub fn new(qubit_index: usize, creg_index: usize) -> Self {
        Self {
            qubit_index,
            creg_index
        }
    }
}

#[derive(Debug)]
pub struct CompiledCircuitMetadata {
    depth: Option<usize>
}

impl CompiledCircuitMetadata {
    pub fn new(depth: Option<usize>) -> Self {
        Self {
            depth
        }
    }
}

impl CompiledCircuit {
    pub fn new(
        num_qubits: usize,
        optimization_level: u8,
        ops: Vec<NativeOp>,
        fused_ops: Vec<FusedOp>,
        measurements: Vec<MeasurementOp>,
        creg_size: usize,
        creg_mapping: Vec<(usize, usize)>,
        metadata: CompiledCircuitMetadata,
    ) -> Self {
        Self {
            num_qubits,
            optimization_level,
            ops,
            fused_ops,
            measurements,
            creg_size,
            creg_mapping,
            metadata,
        }
    }

    pub fn num_qubits(&self) -> usize {
        self.num_qubits
    }

    pub fn optimization_level(&self) -> u8 {
        self.optimization_level
    }

    pub fn ops(&self) -> &Vec<NativeOp> {
        &self.ops
    }

    pub fn fused_ops(&self) -> &Vec<FusedOp> {
        &self.fused_ops
    }

    pub fn measurements(&self) -> &Vec<MeasurementOp> {
        &self.measurements
    }

    pub fn creg_size(&self) -> usize {
        self.creg_size
    }

    pub fn creg_mapping(&self) -> &Vec<(usize, usize)> {
        &self.creg_mapping
    }

    pub fn metadata(&self) -> &CompiledCircuitMetadata {
        &self.metadata
    }
}

impl Debug for CompiledCircuit {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CompiledCircuit").field("num_qubits", &self.num_qubits).field("optimization_level", &self.optimization_level).field("ops", &self.ops).field("fused_ops", &self.fused_ops).field("measurements", &self.measurements).field("creg_size", &self.creg_size).field("creg_mapping", &self.creg_mapping).field("metadata", &self.metadata).finish()
    }
}

/// The ExecutionContext holds everything about the Quantum State
/// This is generated by preparing the CompiledCircuit for execution
pub struct ExecutionContext {
    
}