use intrico::{SequentialCircuit, backend::{BackendConfig, QuantumBackend, StatevectorBackend}};

fn main() {
    // Initializing the circuit
    let mut qc = SequentialCircuit::new(2);

    // Adding gates
    qc.h(0).cx(0, 1);

    // Initializing the backend
    let backend = StatevectorBackend::new(
        BackendConfig::default()
    );

    // Evolving the circuit
    let result = backend.run(qc);

    // Printing the final statevector generated by the circuit
    let statevec = result.final_state();
    println!("Final Statevector: {:.4?}", statevec);

    // Sampling the outcomes from the state
    let sample_result = backend.sample(statevec, 1000, None);

    // Printing the sample result
    println!("Sample Result: {:?}", sample_result);
}