use intrico::SequentialCircuit;
use intrico::backend::{BackendConfig, QuantumBackend, StatevectorBackend};
use intrico::library::QFT;

fn main() {
    // Initializing the circuit to |110⟩ state
    let mut qc = SequentialCircuit::new(3);
    qc.x(2).x(1);

    // Appending the QFT circuit
    let qft = QFT::new(3);
    qc.append(&qft);

    // Initializing the backend
    let backend = StatevectorBackend::new(
        BackendConfig::default()
    );

    // Evolving the circuit
    let result = backend.run(qc);

    // Printing the final statevector generated by the circuit
    let statevec = result.final_state();
    println!("Final Statevector: {:.4?}", statevec);

    // Sampling the outcomes from the state
    let sample_result = backend.sample(statevec, 1000, None);

    // Printing the sample result
    println!("Sample Result: {:?}", sample_result);

}