[package]
name = "intrico"
version = "2.0.3"
edition = "2024"
description = "High-performance Quantum Computing library to simulate quantum circuits with precision and power."
authors = ["Soham Ghugare <soham.ghugare@gmail.com>"]
keywords = [
    "quantum-computing",
    "quantum-technology",
    "quantum-sdk",
    "quantum",
    "rust",
]
categories = ["development-tools", "science", "simulation"]
license = "Apache-2.0"
repository = "https://github.com/Intrico-Labs/intrico"
[dependencies]
intrico-core = { path = "../intrico-core", version = "2.0.3" }
qisa = "0.1.7"
terminal_size = "0.4.3"
rand = "0.10.0"
